### ISSUE TITLE
Percentages are incorrect on table 3.1 Release Stage

### ISSUE THREAD

**Issue by jmelchi** [NRajcevich/dus#22]
The percentages for the pre-dispositional release outcome column should not be calculated the way they are currently. Rather, the percentages should have a denominator of only those pre-dispositional releases that were released to parent or Alternative. There are other pre-dispositional releases where we do not measure the release outcome (i.e Waived to Adult Court) so they should not factor into the calculation. As an example, in the screenshot, the pre-dispositional release outcomes add up to 24 rather than 30. The percentage for those that successfully completed should be 18/24 rather than 18/30.

![image](https://cloud.githubusercontent.com/assets/7317628/6046246/4f058a8e-ac6e-11e4-8298-2fb1dcb90b41.png)

**Comment by NRajcevich** [comment]
Still working on this one. I think there is a different problem here because some of the other counties have strange data. Like where the sub-category has more values then the main one.
